version: '3.8'
services:
  apicultora:
    container_name: apiCultora
    build: .
    environment:
      TZ: Europe/Madrid
    ports:
      - 3335:3335
    volumes:
      - ./logs:/usr/src/logs
    restart: unless-stopped
